# Generated by Django 4.2.5 on 2023-09-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata1',
            name='cell_data2',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
    ]
