# Generated by Django 4.2.5 on 2023-09-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0002_tabledata1_cell_data2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default=1000, max_length=1000),
            preserve_default=False,
        ),
    ]
