# Generated by Django 4.2.5 on 2023-09-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0004_imagemodel_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
