# Generated by Django 4.2.5 on 2023-09-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0005_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='imageTitle',
            field=models.CharField(default=1000, max_length=255),
            preserve_default=False,
        ),
    ]
