# Generated by Django 4.2.5 on 2023-09-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0006_imagemodel_imagetitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/profilePic'),
        ),
    ]
