# Generated by Django 4.2.5 on 2023-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0007_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata1',
            name='cell_data10',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tabledata1',
            name='cell_data11',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tabledata1',
            name='cell_data12',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tabledata1',
            name='cell_data3',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tabledata1',
            name='cell_data4',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tabledata1',
            name='cell_data5',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tabledata1',
            name='cell_data6',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tabledata1',
            name='cell_data7',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tabledata1',
            name='cell_data8',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='tabledata1',
            name='cell_data9',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data2',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='uploads/profilePic'),
        ),
    ]
