# Generated by Django 4.2.5 on 2023-09-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0009_tabledata01'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableData01',
        ),
    ]
