# Generated by Django 4.2.5 on 2023-09-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0010_delete_tabledata01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data10',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data11',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data12',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data2',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data3',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data4',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data5',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data6',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data7',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data8',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data9',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
    ]
