# Generated by Django 4.2.5 on 2023-09-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0012_tabledata01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data2',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data3',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
