# Generated by Django 4.2.5 on 2023-09-26 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0016_alter_tabledata1_cell_data10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledata1',
            name='cell_data10',
        ),
        migrations.RemoveField(
            model_name='tabledata1',
            name='cell_data11',
        ),
        migrations.RemoveField(
            model_name='tabledata1',
            name='cell_data12',
        ),
        migrations.RemoveField(
            model_name='tabledata1',
            name='cell_data4',
        ),
        migrations.RemoveField(
            model_name='tabledata1',
            name='cell_data5',
        ),
        migrations.RemoveField(
            model_name='tabledata1',
            name='cell_data6',
        ),
        migrations.RemoveField(
            model_name='tabledata1',
            name='cell_data7',
        ),
        migrations.RemoveField(
            model_name='tabledata1',
            name='cell_data8',
        ),
        migrations.RemoveField(
            model_name='tabledata1',
            name='cell_data9',
        ),
    ]
