# Generated by Django 4.2.5 on 2023-09-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0017_remove_tabledata1_cell_data10_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TableData01',
        ),
    ]
