# Generated by Django 4.2.5 on 2023-09-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0019_alter_tabledata1_cell_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledata1',
            name='cell_data3',
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata1',
            name='cell_data2',
            field=models.CharField(max_length=255),
        ),
    ]
