# Generated by Django 4.2.5 on 2023-09-26 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0023_alter_tabledata2_cell_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data10',
            field=models.CharField(default=13, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data11',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data12',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data2',
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data3',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data4',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data5',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data6',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data7',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data8',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata2',
            name='cell_data9',
            field=models.CharField(max_length=255),
        ),
    ]
