# Generated by Django 4.2.5 on 2023-09-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0027_tabledata01'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableData001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('num', models.CharField(max_length=255)),
                ('vt', models.FileField(upload_to='uploads/files/% Y/% m/% d/')),
                ('etat', models.CharField(max_length=255)),
                ('tp', models.CharField(max_length=255)),
                ('auditV1', models.FileField(upload_to='uploads/files/% Y/% m/% d/')),
                ('auditV2', models.FileField(upload_to='uploads/files/% Y/% m/% d/')),
                ('auditV3', models.FileField(upload_to='uploads/files/% Y/% m/% d/')),
                ('coffrac', models.CharField(max_length=255)),
            ],
        ),
    ]
