# Generated by Django 4.2.5 on 2023-09-26 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0028_tabledata001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata001',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='auditV1',
            field=models.FileField(blank=True, upload_to='uploads/files/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='auditV2',
            field=models.FileField(blank=True, upload_to='uploads/files/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='auditV3',
            field=models.FileField(blank=True, upload_to='uploads/files/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='cell_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='coffrac',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='etat',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='firstname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='lastname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='num',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='tp',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='vt',
            field=models.FileField(blank=True, upload_to='uploads/files/% Y/% m/% d/'),
        ),
    ]
