# Generated by Django 4.2.5 on 2023-09-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0029_alter_tabledata001_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata001',
            name='auditV1',
            field=models.FileField(blank=True, upload_to='uploads/files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='auditV2',
            field=models.FileField(blank=True, upload_to='uploads/files/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='auditV3',
            field=models.FileField(blank=True, upload_to='uploads/files/%Y/%m/%d/'),
        ),
    ]
