# Generated by Django 4.2.5 on 2023-09-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0030_alter_tabledata001_auditv1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata001',
            name='vt',
            field=models.FileField(blank=True, upload_to='uploads/files'),
        ),
    ]
