# Generated by Django 4.2.5 on 2023-09-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0031_alter_tabledata001_vt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledata001',
            name='vt',
        ),
    ]
