# Generated by Django 4.2.5 on 2023-10-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0035_tabledata001_vt'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_table_auditV1',
            fields=[
                ('file_id', models.CharField(blank=True, max_length=255)),
                ('file_index', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('vt', models.FileField(blank=True, upload_to='uploads/data/<django.db.models.fields.CharField>/auditV1')),
            ],
        ),
    ]
