# Generated by Django 4.2.5 on 2023-10-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0036_file_table_auditv1'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_table_auditv1',
            name='file_format',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
