# Generated by Django 4.2.5 on 2023-10-02 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0037_file_table_auditv1_file_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_table_auditv1',
            old_name='vt',
            new_name='file_save',
        ),
    ]
