# Generated by Django 4.2.5 on 2023-10-02 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0039_alter_file_table_auditv1_file_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file_table_auditv1',
            name='file_save',
            field=models.FileField(blank=True, unique=True, upload_to='uploads/data/auditV1'),
        ),
    ]
