# Generated by Django 4.2.5 on 2023-10-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0040_alter_file_table_auditv1_file_save'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_table_auditV2',
            fields=[
                ('file_index', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_save', models.FileField(blank=True, unique=True, upload_to='uploads/data/auditV1')),
                ('file_format', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='file_table_auditV3',
            fields=[
                ('file_index', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_save', models.FileField(blank=True, unique=True, upload_to='uploads/data/auditV1')),
                ('file_format', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='file_table_vt',
            fields=[
                ('file_index', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_save', models.FileField(blank=True, unique=True, upload_to='uploads/data/auditV1')),
                ('file_format', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
