# Generated by Django 4.2.5 on 2023-10-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0042_file_table_auditfinal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata001',
            name='paiement',
            field=models.BooleanField(default=False),
        ),
    ]
