# Generated by Django 4.2.5 on 2023-10-05 21:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0044_tabledata001_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata001',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
