# Generated by Django 4.2.5 on 2023-10-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0047_remove_user_username_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
