# Generated by Django 4.2.5 on 2023-10-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0049_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
