# Generated by Django 4.2.5 on 2023-10-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0054_updatedxlsxfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='name',
        ),
        migrations.AddField(
            model_name='mymodel',
            name='text_field',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
