# Generated by Django 4.2.5 on 2023-10-10 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0055_remove_mymodel_name_mymodel_text_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='image',
            new_name='image_field',
        ),
    ]
