# Generated by Django 4.2.5 on 2023-10-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0056_rename_image_mymodel_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updatedxlsxfile',
            old_name='image',
            new_name='xlsx_file',
        ),
    ]
