# Generated by Django 4.2.5 on 2023-10-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0057_rename_image_updatedxlsxfile_xlsx_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='image_field_2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='image_field_3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
