# Generated by Django 4.2.5 on 2023-10-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0059_kizeo_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kizeo_model',
            name='Compteur_Electrique_Puissance_souscrite',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_1_Hauteur',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_1_Longueur',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_1_Surface',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_2_Hauteur',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_2_Longueur',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_2_Surface',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_3_Hauteur',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_3_Longueur',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_3_Surface',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_4_Hauteur',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_4_Longueur',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_4_Surface',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
