# Generated by Django 4.2.5 on 2023-10-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0061_alter_kizeo_model_cauffage_photo_appoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kizeo_model',
            name='Cauffage_annee_de_mise_en_oeuvre',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
