# Generated by Django 4.2.5 on 2023-10-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0062_alter_kizeo_model_cauffage_annee_de_mise_en_oeuvre'),
    ]

    operations = [
        migrations.AddField(
            model_name='kizeo_model',
            name='Ventilation_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
