# Generated by Django 4.2.5 on 2023-10-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0063_kizeo_model_ventilation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kizeo_model',
            name='Cauffage_photo_appoint',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Cauffage_photo_fiche_signaletique',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Cauffage_photo_systeme_de_production',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Compteur_Electrique_photo_compteur',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='ECS_photo_appoint',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_1_Photo_Principale',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_2_Photo_Principale',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_3_Photo_Principale',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_4_Photo_Principale',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Ventilation_photo_ventilation',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
    ]
