# Generated by Django 4.2.5 on 2023-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0065_kizeo_model_mur_1_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kizeo_model',
            name='kizeo_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
