# Generated by Django 4.2.5 on 2023-10-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0067_kizeo_model_mur_2_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_1_Composition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_1_Date_d_isolation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_1_Epaisseur_isolant',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_1_Isolation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_1_Photo_plancher_bas',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_1_Position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_1_Preuve_d_isolation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_1_Surface',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_2_Composition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_2_Date_d_isolation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_2_Epaisseur_isolant',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_2_Isolation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_2_Photo_plancher_bas',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_2_Position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_2_Preuve_d_isolation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Plancher_bas_2_Surface',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
