# Generated by Django 4.2.5 on 2023-10-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0069_kizeo_model_plancher_haut_1_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_1_Materiaux',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_1_Menuiserie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_1_Nombre',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_1_Type_de_vitrage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_1_Volets',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_1_menuiseries',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_2_Materiaux',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_2_Menuiserie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_2_Nombre',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_2_Type_de_vitrage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_2_Volets',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Fenetre_type_2_menuiseries',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
    ]
