# Generated by Django 4.2.5 on 2023-10-12 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0070_kizeo_model_fenetre_type_1_materiaux_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kizeo_model',
            name='Porte_1_Materiaux',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Porte_1_Nombre',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Porte_1_Photo_porte',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Porte_1_Type_porte',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Porte_2_Materiaux',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Porte_2_Nombre',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Porte_2_Photo_porte',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Porte_2_Type_porte',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
