# Generated by Django 4.2.5 on 2023-10-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0071_kizeo_model_porte_1_materiaux_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kizeo_model',
            name='signature_data',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
    ]
