# Generated by Django 4.2.5 on 2023-10-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0072_kizeo_model_signature_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kizeo_model',
            old_name='Fenetre_type_1_menuiseries',
            new_name='Fenetre_type_1_Photo',
        ),
        migrations.RenameField(
            model_name='kizeo_model',
            old_name='Fenetre_type_2_menuiseries',
            new_name='Fenetre_type_2_Photo',
        ),
    ]
