# Generated by Django 4.2.5 on 2023-10-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0073_rename_fenetre_type_1_menuiseries_kizeo_model_fenetre_type_1_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Adresse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Annee_de_construction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Besoin_du_client_Chauffage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Besoin_du_client_Isolation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_City',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Date_de_visite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Destination_du_lieu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Etat_d_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Factures',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/db/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Horaire_d_occupation_des_lieux',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Nom_client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Nom_d_intervenant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Nombre_d_occupant',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Nombre_de_niveau',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Preuve_Surface',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Preuve_Surface_Photo',
            field=models.ImageField(blank=True, default='uploads/data/kizeo/db/blank-white.jpg', upload_to='uploads/data/kizeo'),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Scenario_souhaite_par_le_client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Surface_TOTALE',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Surface_ajoute_depuis_moins_de_15_ans',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Tel_client',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='Donnees_Generales_Zip_Code',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='altitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='latitude',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model',
            name='longitude',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
