# Generated by Django 4.2.5 on 2023-10-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0075_alter_kizeo_model_donnees_generales_nombre_d_occupant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Nombre_d_occupant',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Nombre_de_niveau',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Surface_TOTALE',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Surface_ajoute_depuis_moins_de_15_ans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Tel_client',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Zip_Code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
