# Generated by Django 4.2.5 on 2023-10-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0076_alter_kizeo_model_donnees_generales_nombre_d_occupant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata001',
            name='etat_vt',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
