# Generated by Django 4.2.5 on 2023-10-15 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0077_tabledata001_etat_vt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Date_de_visite',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
