# Generated by Django 4.2.5 on 2023-10-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0078_alter_kizeo_model_donnees_generales_date_de_visite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Zip_Code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
