# Generated by Django 4.2.5 on 2023-10-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0079_alter_kizeo_model_donnees_generales_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Tel_client',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
