# Generated by Django 4.2.5 on 2023-10-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0080_alter_kizeo_model_donnees_generales_tel_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Nombre_d_occupant',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Nombre_de_niveau',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Surface_TOTALE',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Surface_ajoute_depuis_moins_de_15_ans',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
