# Generated by Django 4.2.5 on 2023-10-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0081_alter_kizeo_model_donnees_generales_nombre_d_occupant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='kizeo_model_Pieces',
            fields=[
                ('Pieces_index', models.AutoField(primary_key=True, serialize=False)),
                ('kizeo_id', models.CharField(blank=True, max_length=100)),
                ('Pieces_image_1', models.ImageField(blank=True, null=True, upload_to='uploads/data/kizeo')),
                ('Pieces_image_2', models.ImageField(blank=True, null=True, upload_to='uploads/data/kizeo')),
                ('Pieces_image_3', models.ImageField(blank=True, null=True, upload_to='uploads/data/kizeo')),
                ('Pieces', models.CharField(blank=True, max_length=100)),
                ('Chauffage', models.CharField(blank=True, max_length=100)),
                ('Mansardee', models.CharField(blank=True, max_length=100)),
                ('HSP', models.FloatField(blank=True, default=0.0)),
                ('Lonqueur', models.FloatField(blank=True, default=0.0)),
                ('Largeur', models.FloatField(blank=True, default=0.0)),
                ('Surface', models.FloatField(blank=True, default=0.0)),
                ('HSF', models.FloatField(blank=True, default=0.0)),
                ('HPP', models.FloatField(blank=True, default=0.0)),
                ('LP', models.FloatField(blank=True, default=0.0)),
                ('S_rampants_1', models.FloatField(blank=True, default=0.0)),
                ('Decrochement_Lonqueur', models.FloatField(blank=True, default=0.0)),
                ('Decrochement_Largeur', models.FloatField(blank=True, default=0.0)),
                ('Decrochement_Surface', models.FloatField(blank=True, default=0.0)),
                ('Surface_nette', models.FloatField(blank=True, default=0.0)),
                ('Menuiseries_F', models.CharField(blank=True, max_length=1000)),
                ('Menuiseries_L', models.FloatField(blank=True, default=0.0)),
                ('Menuiseries_H', models.FloatField(blank=True, default=0.0)),
                ('Menuiseries_N', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
