# Generated by Django 4.2.5 on 2023-10-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0082_kizeo_model_pieces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kizeo_model_pieces',
            old_name='Decrochement_Lonqueur',
            new_name='Decrochement_Longueur',
        ),
        migrations.RenameField(
            model_name='kizeo_model_pieces',
            old_name='Lonqueur',
            new_name='Longueur',
        ),
        migrations.AddField(
            model_name='kizeo_model_pieces',
            name='IF_mansardee',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kizeo_model_pieces',
            name='Niveau',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kizeo_model_pieces',
            name='S_rampants_2',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
