# Generated by Django 4.2.5 on 2023-10-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0083_rename_decrochement_lonqueur_kizeo_model_pieces_decrochement_longueur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kizeo_model_pieces',
            name='IF_mansardee',
            field=models.BooleanField(default=False),
        ),
    ]
