# Generated by Django 4.2.5 on 2023-10-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0084_alter_kizeo_model_pieces_if_mansardee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agent',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
