# Generated by Django 4.2.5 on 2023-10-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0086_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='uploads/default_user_avatar.png', upload_to='uploads/profilePic'),
        ),
    ]
