# Generated by Django 4.2.5 on 2023-10-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0089_alter_kizeo_model_porte_1_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata001',
            name='auditeur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
