# Generated by Django 4.2.5 on 2023-10-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0090_tabledata001_auditeur_alter_tabledata001_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
