# Generated by Django 4.2.5 on 2023-10-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0091_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata001',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tabledata001',
            name='precaite',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
