# Generated by Django 4.2.5 on 2023-10-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0092_tabledata001_email_tabledata001_precaite'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata001',
            name='ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabledata001',
            name='be',
            field=models.BooleanField(default=False),
        ),
    ]
