# Generated by Django 4.2.5 on 2023-10-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0093_tabledata001_ai_tabledata001_be'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='be',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='com_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
