# Generated by Django 4.2.5 on 2023-10-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0094_user_ai_user_be_user_com_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata001',
            name='bureau_d_etude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
