# Generated by Django 4.2.5 on 2023-10-28 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0095_tabledata001_bureau_d_etude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabledata001',
            old_name='coffrac',
            new_name='cofrac',
        ),
    ]
