# Generated by Django 4.2.5 on 2023-10-29 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0096_rename_coffrac_tabledata001_cofrac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities_audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Activity_in', models.CharField(blank=True, max_length=255)),
                ('Activity_before', models.CharField(blank=True, max_length=255)),
                ('Activity_after', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
