# Generated by Django 4.2.5 on 2023-10-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0097_activities_audit'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities_audit',
            name='Activity_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activities_audit',
            name='Activity_table',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activities_audit',
            name='Activity_user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
