# Generated by Django 4.2.5 on 2023-10-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0098_activities_audit_activity_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_or_AGENT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AI_or_AGENT_id', models.CharField(blank=True, max_length=255)),
                ('AI_or_AGENT_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
