# Generated by Django 4.2.5 on 2023-10-29 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0099_ai_or_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_table_auditfinal',
            name='file_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file_table_auditv1',
            name='file_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file_table_auditv2',
            name='file_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file_table_auditv3',
            name='file_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file_table_vt',
            name='file_removed',
            field=models.BooleanField(default=False),
        ),
    ]
