# Generated by Django 4.2.5 on 2023-10-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0100_file_table_auditfinal_file_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_table_auditv1',
            name='file_removed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file_table_auditv1',
            name='file_removed_user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
