# Generated by Django 4.2.5 on 2023-10-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0102_file_table_auditv2_file_removed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_table_auditfinal',
            name='file_removed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file_table_auditfinal',
            name='file_removed_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file_table_auditv3',
            name='file_removed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file_table_auditv3',
            name='file_removed_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file_table_vt',
            name='file_removed_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='file_table_vt',
            name='file_removed_user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
