# Generated by Django 4.2.5 on 2023-10-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0103_file_table_auditfinal_file_removed_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_table_vt',
            old_name='file_removed_user',
            new_name='file_removed_user_FN',
        ),
        migrations.AddField(
            model_name='file_table_vt',
            name='file_removed_user_LN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file_table_vt',
            name='file_removed_user_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
