# Generated by Django 4.2.5 on 2023-10-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0104_rename_file_removed_user_file_table_vt_file_removed_user_fn_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_table_auditfinal',
            old_name='file_removed_user',
            new_name='file_removed_user_FN',
        ),
        migrations.RenameField(
            model_name='file_table_auditv1',
            old_name='file_removed_user',
            new_name='file_removed_user_FN',
        ),
        migrations.RenameField(
            model_name='file_table_auditv2',
            old_name='file_removed_user',
            new_name='file_removed_user_FN',
        ),
        migrations.RenameField(
            model_name='file_table_auditv3',
            old_name='file_removed_user',
            new_name='file_removed_user_FN',
        ),
        migrations.AddField(
            model_name='file_table_auditfinal',
            name='file_removed_user_LN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file_table_auditfinal',
            name='file_removed_user_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file_table_auditv1',
            name='file_removed_user_LN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file_table_auditv1',
            name='file_removed_user_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file_table_auditv2',
            name='file_removed_user_LN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file_table_auditv2',
            name='file_removed_user_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file_table_auditv3',
            name='file_removed_user_LN',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='file_table_auditv3',
            name='file_removed_user_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
