# Generated by Django 4.2.5 on 2023-10-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0106_alter_file_table_auditfinal_file_removed_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata001',
            name='fini_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
