# Generated by Django 4.2.5 on 2023-10-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0109_tabledata001_fini_time_checker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata001',
            name='fini_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
