# Generated by Django 4.2.5 on 2023-10-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0111_tabledata001_envoye_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='file_table_AdA',
            fields=[
                ('file_removed_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('file_removed_user_email', models.CharField(blank=True, max_length=255)),
                ('file_removed_user_FN', models.CharField(blank=True, max_length=255)),
                ('file_removed_user_LN', models.CharField(blank=True, max_length=255)),
                ('file_removed', models.BooleanField(default=False)),
                ('file_index', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_save', models.FileField(blank=True, unique=True, upload_to='uploads/data/vt')),
                ('file_format', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='file_table_comm',
            fields=[
                ('file_removed_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('file_removed_user_email', models.CharField(blank=True, max_length=255)),
                ('file_removed_user_FN', models.CharField(blank=True, max_length=255)),
                ('file_removed_user_LN', models.CharField(blank=True, max_length=255)),
                ('file_removed', models.BooleanField(default=False)),
                ('file_index', models.AutoField(primary_key=True, serialize=False)),
                ('file_id', models.CharField(blank=True, max_length=255)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_save', models.FileField(blank=True, unique=True, upload_to='uploads/data/vt')),
                ('file_format', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
