# Generated by Django 4.2.5 on 2023-10-30 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0112_file_table_ada_file_table_comm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities_audit',
            old_name='Activity_in',
            new_name='Activity_project_id',
        ),
    ]
