# Generated by Django 4.2.5 on 2023-10-30 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0113_rename_activity_in_activities_audit_activity_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities_audit',
            name='Activity_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activities_audit',
            name='Activity_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='activities_audit',
            name='Activity_user_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
