# Generated by Django 4.2.5 on 2023-10-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0114_activities_audit_activity_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities_audit',
            name='Activity_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='etat',
            field=models.CharField(blank=True, default='A realiser', max_length=255),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='etat_vt',
            field=models.CharField(blank=True, default='En cours', max_length=255),
        ),
    ]
