# Generated by Django 4.2.5 on 2023-11-02 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0116_activities_audit_activity_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai_or_agent',
            old_name='AI_or_AGENT_name',
            new_name='comp_name',
        ),
        migrations.AddField(
            model_name='ai_or_agent',
            name='ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ai_or_agent',
            name='be',
            field=models.BooleanField(default=False),
        ),
    ]
