# Generated by Django 4.2.5 on 2023-11-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0118_activities_audit_activity_add_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='message_box_1',
            name='profile_pic',
            field=models.ImageField(blank=True, default='uploads/default_user_avatar.png', upload_to='uploads/profilePic'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Cauffage_photo_appoint',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Cauffage_photo_fiche_signaletique',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Cauffage_photo_systeme_de_production',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Compteur_Electrique_photo_compteur',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Factures',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Donnees_Generales_Preuve_Surface_Photo',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='ECS_photo_appoint',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_1_Photo_Principale',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_2_Photo_Principale',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_3_Photo_Principale',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Facade_4_Photo_Principale',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Fenetre_type_1_Photo',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Fenetre_type_2_Photo',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Mur_1_Photo_mur',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Mur_2_Photo_mur',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Plancher_Haut_1_Photo_plancher_bas',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Plancher_Haut_2_Photo_plancher_bas',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Plancher_bas_1_Photo_plancher_bas',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Plancher_bas_2_Photo_plancher_bas',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Porte_1_Photo_porte',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Porte_2_Photo_porte',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Saisie_par_piece_Signature_client',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Saisie_par_piece_Signature_intervenant',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='Ventilation_photo_ventilation',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
        migrations.AlterField(
            model_name='kizeo_model',
            name='signature_data',
            field=models.ImageField(blank=True, upload_to='uploads/data/kizeo'),
        ),
    ]
