# Generated by Django 4.2.5 on 2023-11-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0119_message_box_1_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities_audit',
            name='Activity_be',
            field=models.BooleanField(default=False),
        ),
    ]
