# Generated by Django 4.2.5 on 2023-11-17 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0120_activities_audit_activity_be'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities_be',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Activity_id', models.CharField(blank=True, max_length=255)),
                ('Activity_user', models.CharField(blank=True, max_length=255)),
                ('Activity_user_email', models.CharField(blank=True, max_length=255)),
                ('Activity_table', models.CharField(blank=True, max_length=255)),
                ('Activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Activity_project_id', models.CharField(blank=True, max_length=255)),
                ('Activity_name', models.CharField(blank=True, max_length=255)),
                ('Activity_before', models.CharField(blank=True, max_length=255)),
                ('Activity_after', models.CharField(blank=True, max_length=255)),
                ('Activity_add', models.BooleanField(default=False)),
                ('Activity_add_2', models.BooleanField(default=False)),
                ('Activity_edit', models.BooleanField(default=False)),
                ('Activity_delete', models.BooleanField(default=False)),
                ('Activity_be', models.BooleanField(default=False)),
            ],
        ),
    ]
