# Generated by Django 4.2.5 on 2023-12-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0121_activities_be'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata001',
            name='Envoye_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tabledata001',
            name='fini_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file_table_ada',
            name='file_removed_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='file_table_comm',
            name='file_removed_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='file_table_vt',
            name='file_removed_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
