# Generated by Django 4.2.5 on 2023-12-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0122_tabledata001_envoye_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata001',
            name='Envoye_by_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tabledata001',
            name='fini_by_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
