# Generated by Django 4.2.5 on 2023-12-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0123_alter_tabledata001_envoye_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata001',
            name='Modification_Faite_by_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tabledata001',
            name='Modification_Faite_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tabledata001',
            name='Modification_Faite_time_checker',
            field=models.BooleanField(default=False),
        ),
    ]
