# Generated by Django 4.2.5 on 2023-12-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0124_tabledata001_modification_faite_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities_be',
            name='Activity_add_client',
            field=models.BooleanField(default=False),
        ),
    ]
