# Generated by Django 4.2.5 on 2023-12-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0125_activities_be_activity_add_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auditeur',
            field=models.BooleanField(default=False),
        ),
    ]
