# Generated by Django 4.2.5 on 2023-12-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ERapp', '0126_user_auditeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata001',
            name='Modification_Faite_time_checker_2',
            field=models.BooleanField(default=False),
        ),
    ]
